### ISSUE TITLE
Add sshfs option "follow_symlinks"

### ISSUE THREAD

**Issue by NotNorom** [ltsp/ltsp#114]
Hey!

I have a setup in which users need access to a shared folder `/group`.
Currently I have a symlink in their home directories pointing to that path, as it's easier for the users to use.
The problem: I am using sshfs and per default it is not following symlinks which results in a broken link on the client system because `/groups` does not exist.

By adding `follow_symlinks` to the `sshfs_params` variable inside `client/login/pamltsp` this setup works.

My question: Is it possible that the `follow_symlinks` is set per default or is there a way to provide sshfs with this option without modifying the file above? My setup might just be flawed from the get go, if so: any feedback is appreciated :)

Thank you!

**Comment by alkisg** [comment]
As far as I can remember, enabling follow_symlinks breaks chromium, .Xauthority and .ICEauthority, while if fixes gnome-keyring-daemon.

To enable follow_symlinks, lightdm should be configured to put .Xauthority in the XDG_RUNTIME dir, and a workaround should be found for chromium. I'm not sure if other display managers have such an option though.

Otherwise, an option similar to the LTSP5 EXTRA_MOUNTS should be implemented, i.e. additional sshfs mounts that do have follow_symlinks enabled by default.

Due to lack of time, all these will need to wait until next year though.

**Comment by alkisg** [comment]
Btw, you can of course use NFS for the /home/Shared folder now, with whatever security implications that entails.

**Comment by sebastiendu** [comment]
In LTSP 5, SSH_FOLLOW_SYMLINKS can be set to True in lts.conf but it is a dangerous feature.
I would advise against it, because it makes server-side symbolic links appear as normal folders to the SSH fat client.
A file manager running on the fat client might recursively delete whole shared subfolders, following symlinks without knowing it.

**Comment by alkisg** [comment]
This was partially implemented as the SSH_OPTIONS ltsp.conf parameter, see https://github.com/ltsp/ltsp/issues/338#issuecomment-735230997 for a usage example.

I agree with LTSP5 and sebastiendu to not enable follow_symlinks as the default for HOME mounting; it could be better for a shared directory.

Closing this issue; if support for EXTRA_MOUNTS is needed in the future, we can file a new one. EXTRA_MOUNTS could also be implemented using a different user account and ssh keys; e.g. /home/shared could be mounted with a nautilus `sftp://shared@server:share` bookmark, and appropriate ssh keys in the users ~/.ssh folders.
