### ISSUE TITLE
[LTSP 19] Restrict ssh usage

### ISSUE THREAD

**Issue by Tsimwi** [ltsp/ltsp#128]
Hello everyone,

I am in the process of hardening my clients and I wondered if it was possible to restrict ssh usage on them. I doubt it is possible to completely prevent `ssh` command usage, but at least I'd like to achieve something like this :

https://help.ubuntu.com/community/UbuntuLTSP/FatClientWithChrootHomeDir

The idea is not to allow a user to get out of his home directory when he ssh into the server.
Unfortunately, this document is not up-to-date and I couldn't make it work. My test client is stuck at login with the error `read:Connection reset by peer.`

I suspect that libs/binaries/files might be missing in the home directory of my client. Does somebody did this before or has an idea how to do it ?

Thanks!

**Comment by alkisg** [comment]
I transferred this issue from the ltsp/community tracker to the ltsp/ltsp tracker, marking it as an ltsp issue.

If noone objects, I'll implement the `ssh -ns server sftp` approach next year when I'll have some free time. This will make it possible to completely disallow ssh logins, and only allow sftp access, without involving chroots at all.

**Comment by alkisg** [comment]
An alternative way to configure ssh so that users only see things under /home and not /, is to put this at the end of /etc/ssh/sshd_config:

```shell
# /etc/ssh/sshd_config.d can't be used, see https://bugs.debian.org/961007
Match Group *,!sudo,!root
    ChrootDirectory /home
    ForceCommand internal-sftp -d %u
Match all
```

That way there's no need to use bind-mounts or symlinks, and it also allows sudoers to properly login via ssh. Note that the client is supposed to run `sshfs user@server: mountpoint`, without specifying a server path, which is what LTSP already does.

**Comment by alkisg** [comment]
Fix committed in 047f7d16ff0af0ad2e63d27ff467df95db8d6c99, closing.

**Comment by jeremy-walker** [comment]
> An alternative way to configure ssh so that users only see things under /home and not /, is to put this at the end of /etc/ssh/sshd_config:

```
# /etc/ssh/sshd_config.d can't be used, see https://bugs.debian.org/961007
Match Group *,!sudo,!root
    ChrootDirectory /home
    ForceCommand internal-sftp -d %u
Match all
```
If I add the above to `/etc/ssh/sshd_config` on the server, users on the LTSP clients are able to login to the desktop, as well as unlock from the screensaver, however they are unable to change their passwords using something like `/usr/bin/mate-about-me`. Is this expected behavior or do I need to investigate it further at my end?

**Comment by alkisg** [comment]
It's expected behavior, see https://github.com/ltsp/ltsp/issues/148#issuecomment-686927698.
