### ISSUE TITLE
Customize the greeter user list

### ISSUE THREAD

**Issue by fottsia** [ltsp/ltsp#33]
Some greeters support displaying a list of users that can be selected by the mouse, thus avoiding the need to type the username.

This, in combination with the existing PASSWORDS_x ltsp.conf option, can be very handy for younger students that aren't yet very familiar with usernames and passwords or even the keyboard.

For example, in pc01, only the guest account "guest01" and the "a1-01", "a2-01" from class "a" would show up, allowing these users to click on their names and then just press Enter to login.

**Comment by alkisg** [comment]
Fix committed in https://github.com/ltsp/ltsp/commit/99c1a78bf861a439cc28e04faba8b5384e05b8af.

This only works with "slick-greeter" currently, so I didn't yet document it in `man ltsp.conf`.
An example ltsp.conf entry for this is:

```shell
LTSPDM_USERS="(guest|[ab][0-9]*)-*%{HOSTNAME#pc}"
```

Assuming that the clients are named "pc01, pc02, ...", the guests "guest01, guest02, ...", and the users something like like "a1-01, a201, b3-03, c1-01, ...",
then, on pc01, only guest01, a1-01 and a201 will be shown in the greeter list.

Sending a PPA build for this, please test and report if it doesn't work as expected.

**Comment by dgroos** [comment]
Due to issues with gdm3 and Epoptes, I've switched to lightdm.
```
sudo apt install lightdm
(During installation I selected "OK" to config question, then selected, "lightdm".)
```
This solved the issues with epoptes (first, couldn't broadcast to clients and second, couldn't shutdown a client when a student had left a firefox modal window unresolved on the screen and it timed out). Works like a charm now. 

Now with the new DM I needed to readdress hiding the full user list on the login screen as I've got about 150 users on my system. I followed [the instructions](https://wiki.ubuntu.com/LightDM), first creating the proper config file:
```
sudo touch /etc/lightdm/lightdm.conf.d/50-myconfig.conf
```
Then edited it with:
```
sudo nano /etc/lightdm/lightdm.conf.d/50-myconfig.conf
```
So that it said:
```
[Seat:*]
greeter-hide-users=true
```
I then ran all of these (just to be safe :) )
```
sudo ltsp image /
sudo ltsp nfs
sudo ltsp ipxe
sudo ltsp initrd
```
But, while the clients do use lightdm, they still show the full list of users. Is there a way to make the client computers pick up this configuration?

**Comment by alkisg** [comment]
Hi dgrooos,

run `man ltsp.conf` and see the LIGHTDM_CONF="greeter-hide-users=true" line.
You don't need anything more than that; delete that 50-myconfig.conf that you created.

**Comment by dgroos** [comment]
Ah, will do, thanks!
David

**Comment by dgroos** [comment]
Thanks! It worked great.
Seems like this would be another useful wiki page for me to make, combined with advise to not use gdk3 if you are going to use epoptes, yes?

**Comment by alkisg** [comment]
Yeah until I have some time to fix epoptes to work properly with the multiple VTs that gdm3 spawns, using epoptes with gdm3 isn't a good choice.
