### ISSUE TITLE
AD support with home directory creation

### ISSUE THREAD

**Issue by carles-alemany** [ltsp/ltsp#407]
Hi everyone, and thank you for this great project!

We've been using LTSP5 over the last 8 years, and now it's time to upgrade. On our old setup, which is still running, we have a Samba4 AD VM + LTSP5 VM serving different chroots to fat clients. LTSP server is joined to AD via pbis-open, fat-clients are able to authenticate with domain credentials and, every time a new user logs in, a new home directory is created into the LTSP server.

We tried to replicate this setup with the new LTSP version, working with chroots as we did before. At this point, everything works, users are able to login with AD credentials but home folders are being created on the clients, not on the server, so everytime a client is disconnected, user's home directory is lost.

What we've done:

Create a new chroot and assign a password to root.
Export the new created chroot via NFS in order to boot from a client (https://github.com/ltsp/ltsp/wiki/chroots “Booting the chroot with a client”).
Boot a client using the exported chroot.
Join the chroot to AD with realmd-join, following these steps: https://computingforgeeks.com/join-ubuntu-debian-to-active-directory-ad-domain/
After joining the chroot to AD, its name (focal) is being shown as a new computer inside the AD.
Shutdown the client
Update chroot on the server (sudo update ltsp focal)
After doing these steps, a client can boot from the newly created image and we're able to login with a domain user and access SMB shares. Everything works except home directory, which is being created at the client instead of the server.

Also, during the login, the client shows this message but then logs in without issues:
![108489844-56b67a80-72a2-11eb-8ca3-ba48c8de0850](https://user-images.githubusercontent.com/79309152/109282870-65f77400-781e-11eb-94be-58900ed74e0c.png)

Any ideas on how to automatically create user's home directory on the server at login? I'll be more than happy to make a wiki page if I can make it work.

Thank you!

**Comment by alkisg** [comment]
Hello, what happens if you login as root on the client, and then you type this command?

```shell
ssh username@server
```

In the place of `username`, put an LDAP user.
Do not replace `server` with a real hostname, because the LTSP clients know the LTSP server with that codename, "server".

Are you able to SSH to the server that way?
If yes, can you install and configure pam_mkhomedir on the server, so that the home directory of SSH users is automatically created?

**Comment by carles-alemany** [comment]
Hello, 

I've tried to login as root on the client, and I get this message: "User root can't auth via pamltsp"

So, I logged in as a user with sudo permissions on the client, and then I did:

`sudo su`

Then, as root:

`root@ltsp249:/home/adminlocal# ssh profetest2@domain.lan@server`

After putting the password, this message appears:

`Permission denied, please try again.`

So, I'm unable to login via ssh to the server.

Here are the outputs you asked for: 

**SERVER**:
The command does not give any output at all:
`adminlocal@S-208:~$ getent passwd profetest2@domain.lan`

**CLIENT**:
`adminlocal@ltsp249:~$ getent passwd profetest2@domain.lan
profetest2@domain.lan:*:1455407248:1455400513:Profetest 2:/home/profetest2@domain.lan:/bin/bash`

Maybe I should join the server to the domain too, doing the same steps I did with the chroot?

Thank you

**Comment by alkisg** [comment]
To log in as root on a client, follow the last example of https://ltsp.org/man/ltsp.conf/.
You don't need to, as you already have a way to do it.

In your old LTSP5 setup, you should have been able to run `ssh user@server`, otherwise SSHFS wouldn't work. If that's not the case now, it means you omitted something while setting up the system.

So yeah either join the server to AD, or switch to NFS home instead of SSHFS home.

I'll move this issue to discussions as it's not about a bug in the LTSP code.
