### ISSUE TITLE
Boot Partition

### ISSUE THREAD

**Issue by fwskvogt** [ltsp/ltsp#43]
In a Debian Buster installation I tried to run 

`ltsp image /`

At the end of the output I get:

`Could not locate vmlinuz and initrd.img in /srv/ltsp/images/x86_64.img`

I think this is because I have a seperate /boot partition which is not mounted at the start of the process of building the image. The output mentions:

`Running: mount --bind --make-private -o ro / /tmp/tmp.1kY9JjhRSf/root/`

So all the files in the original /boot directory are missing in /tmp/tmp.1kY9JjhRSf/root/.

What can I do?

With kind regards

Jürgen Vogt

**Comment by alkisg** [comment]
Ah that's a second problem. It's probably caused because overlayfs doesn't use the "merged view" of the mounts by default, but only a single mount. In LTSP5, we handled that with [additional overlay mounts](https://git.launchpad.net/ltsp/tree/server/ltsp-update-image#n149), we should probably do the same here.

I'll need a few days to resolve that; in the mean time, please do something like this as a workaround:

```shell
mount --bind / /mnt
cp -a /boot/. /mnt/boot/
umount /mnt
ltsp image /
```

I.e. copy the contents of the /boot partition to the /boot folder of the / partition, before calling `ltsp image /`.

**Comment by alkisg** [comment]
Btw, I just moved this issue from the [community issues](https://github.com/ltsp/community/issues) to [ltsp issues](https://github.com/ltsp/ltsp/issues) as it proved to be a bug.

I do love this "ltsp" vs "community" issues separation!
Something starts as a discussion and it ends up being a bug? We just move it from community/issues to ltsp/issues.
Or the opposite, something starts as a bug but the user just needed advice? We move it to community/issues.

There's no need for users to have two different accounts/interfaces (e.g. launchpad and sourceforge mailing lists for LTSP5), and there's no need to restart the conversation after the move. I hope github won't mind us abusing a bit the issues tracker for discussions, but it's a great tool!

**Comment by fwskvogt** [comment]
I successfully applied the workaround . I'm seeing forward to your
solution.

Jürgen

Am Samstag, den 12.10.2019, 22:45 -0700 schrieb Alkis Georgopoulos:
> Ah that's a second problem. It's probably caused because overlayfs
> doesn't use the "merged view" of the mounts by default, but only a
> single mount. In LTSP5, we handled that with [additional overlay
> mounts](
> https://git.launchpad.net/ltsp/tree/server/ltsp-update-image#n149),
> we should probably do the same here.
> 
> I'll need a few days to resolve that; in the mean time, please do
> something like this as a workaround:
> 
> ```shell
> mount --bind / /mnt
> cp -a /boot/. /mnt/boot/
> umount /mnt
> ltsp image /
> ```
> 
> I.e. copy the contents of the /boot partition to the /boot folder of
> the / partition, before calling `ltsp image /`.
> 
-- 
FREIE WALDORFSCHULE KASSEL
Jürgen Vogt
Hunrodstraße 17
34131 Kassel

Telefon 0561 935130
Fax     0561 9351316
Email   j.vogt@waldorfschule-kassel.de
www     www.waldorfschule-kassel.de

**Comment by alkisg** [comment]
Small status update:

the reason I haven't implemented this yet, is that this specific part needs a code redesign.

The old code performs all mounts and submounts and then does a tmpfs/overlay on top of the result. But overlayfs doesn't support multiple lowerdirs in varying subdirs ([they all go in a single dst/](https://www.kernel.org/doc/Documentation/filesystems/overlayfs.txt)), so another approach is needed.

With the new approach, a tmpfs will be created first, and then all submounts will be tmpfs/overlays on top of the appropriate subdirs. This will make it impossible to boot a client in "ltsp mode" and **not** have a tmpfs/overlay for /. If this is ever needed, we'll need another small redesign then.

**Comment by enoch85** [comment]
Hey, writing here as my issue was closed and referring to this one. 

1. The workaround worked.
2. Another issue arise which is that ipxe requires `filename.xyz.0`. Problem is that the files `undionly.kpxe` and `ltsp.ipxe` aren't named .0 at the end. To solve that I simply copied the original files and added .0 after. Now everything works like a charm!

**Comment by alkisg** [comment]
iPXE worked fine without the .0 extension in all the tests I've done, and AFAIK no other LTSP user had that problem.

Can you open another issue about that problem, and mention more details?

Btw when installing dnsmasq, normally it won't start at all because systemd-resolved already has the 53 port open, so in the new issue also mention how you installed dnsmasq etc, i.e. what was different in your case compared to the [installation page](https://ltsp.github.io/docs/installation/) instructions.

**Comment by schweer-guest** [comment]
I managed to work around the multiple partion issue using a plain mksquashfs command:

Instead of running `ltsp image /`
I ran these commands:
```
cp /usr/share/ltsp/server/image/image.excludes /tmp/excludes
if [ -f /etc/ltsp/image-local.excludes ] ; then
	cat /etc/ltsp/image-local.excludes >> /tmp/excludes
fi
mksquashfs / /srv/ltsp/images/$(uname -m).img -noappend -wildcards -ef /tmp/excludes
rm /tmp/excludes
ltsp kernel
```
This worked for me however fancy the partitioning has been.

Wolfgang

**Comment by alkisg** [comment]
Note that this has security implications, e.g. it leaves the server /etc/shadow in the image without cleaning up the server user accounts (no cleanup phase).

**Comment by schweer-guest** [comment]
Hi Alkis, thanks for the security related warning.

In the case of [Debian Edu](https://blends.debian.org/edu), the user accounts are kept in LDAP (homedirs are made available using kerberized NFS and autofs-ldap).
Instead of running `ltsp image /`, this worked for me on both the main server (where LDAP is located) and a workstation (turned into a separate LTSP server).
```
TEMPDIR=$(mktemp -d)
mkdir $TEMPDIR/etc
cp /etc/shadow* $TEMPDIR/etc
sed -i '/root:/d' /etc/shadow
sed -i '/root:/d' /etc/shadow-
cp /usr/share/ltsp/server/image/image.excludes $TEMPDIR/excludes
if [ -f /etc/ltsp/image-local.excludes ] ; then
	cat /etc/ltsp/image-local.excludes >> $TEMPDIR/excludes
fi
mksquashfs / /srv/ltsp/images/$(uname -m).img -noappend -wildcards -ef $TEMPDIR/excludes
cp $TEMPDIR/etc/shadow* /etc
rm -rf $TEMPDIR
ltsp kernel
```
I hope that this is the right way to fix the security issue.

**Comment by alkisg** [comment]
I'm planning to have this fixed for the LTSP 20.01 release; hang on. :)

**Comment by schweer-guest** [comment]
Great, thank you.

**Comment by alkisg** [comment]
Fix committed in 147a6593d60a4aaa0105ab7b378f546ca01b9bc2.

@schweer-guest, @fwskvogt, or anyone else affected, could you please try the latest build from the [proposed PPA](https://ltsp.org/advanced/proposed-ppa/) and see if it solves your issue without any regressions, so that we upload LTSP 20.01 to Debian? Thanks!

Remember that submounts aren't automatically discovered, so a syntax like the one [described here](https://github.com/ltsp/ltsp/issues/43#issuecomment-541269010) is necessary.

**Comment by schweer-guest** [comment]
@alkisg
Thanks for fixing this issue.
Test on a system with separate partitions for /boot, /usr and /var has been successful (running `ltsp image /,,/boot,subdir=boot,,/usr,subdir=usr,,/var,subdir=var`).

There's a regression, though: additional image excludes are no longer evaluated. I had to temporarily add those to `/usr/share/ltsp/server/image/image.excludes` to get it working after I noticed that directories contained in /etc/ltsp/image-local.excludes were still showing up in the image; explicitly using ADD_IMAGE_EXCLUDES to specify the excludes file in ltsp.conf didn't work either.

**Comment by alkisg** [comment]
Hi @schweer-guest,

I re-tested ADD_IMAGE_EXCLUDES and it's still working fine for me.
Specific tests:

1) This excludes everything under /usr: 

```shell
[server]
ADD_IMAGE_EXCLUDES="usr/*"
```

2) And this does the same:

```shell
[server]
ADD_IMAGE_EXCLUDES="/etc/ltsp/image-local.excludes"
```

...where that file contains the line: `usr/*`.

Make sure you're putting those under [server], not e.g. under [clients]...

The related changes for image excludes were **not** done in this recent commit; they were done in e780fbb61c42400c9dc659a95014925bae0b1a78.

**Comment by schweer-guest** [comment]
Hi @alkisg,
thanks for the feed back and sorry for the noise: I was misled by this line still contained  in  `/usr/share/ltsp/server/image/image.excludes`:

`# Create /etc/ltsp/image-local.excludes to add more entries;`

I guess the above line should be dropped.

And then, you are right: I placed the ADD_IMAGE_EXCLUDES statement accidently below [clients].
So to summarize: **It's all fine with ltsp 20.01-1**.
One thing left: Please add `Closes: #946946 ` to the debian/changelog line containing #43, so that the Debian BTS gets notified to close the bug, see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=946946

**Comment by alkisg** [comment]
True, that documentation line needs to go.

I'm reusing the changelog in the github announcements, for example https://github.com/ltsp/ltsp/issues/1#issuecomment-562498648, so Closes: #946946 there would be considered a github issue link... I'm not sure what's the best way to handle that, but for the moment I was trying to completely avoid "Closes". Additionally, I would like to minimize the use of distro-specific bugs as much as possible, in favor of the upstream bug tracker...

I'll rethink that approach in the future when I'll have more free time... maybe then I'll be able to maintain two changelogs for each release, and upstream and a Debian one.

**Comment by schweer-guest** [comment]
ok, I will close the Debian bug then.
Thanks for your work on LTSP!

**Comment by alkisg** [comment]
You're welcome, thanks for testing.

I amended the aforementioned comment in 375c9f8453d303371c6da56e4b02a6d6f64610f4.

**Comment by alkisg** [comment]
Ouch, even with all the delay to find time to do this properly, the fix broke netbooting live CDs.

In live CDs, we want to mount the squashfs image first, then find the overlay module inside it, as it's not otherwise available in the initramfs, and then do the tmpfs/overlay merge.
While this #43 issue required the opposite, to do the tmpfs/overlay first and then to start the mounting process.

...I'll try to find some workaround that doesn't result in completely unreadable code...

**Comment by danboid** [comment]
LTSP was failing to find my kernel and initrd at the end of creating the image so I ran:

```
mount --bind / /mnt
cp -a /boot/. /mnt/boot/
umount /mnt
ltsp image /
```

As advised above and that has fixed the missing kernel problem at least.

The problem here though is that this issue was closed almost a year ago but the problem persists in the latest PPA version of LTSP. If this can't be fixed then shouldn't these extra steps be mentioned in the installation guide?

**Comment by alkisg** [comment]
Hi danboid,

what you did was not the correct solution. I replied with the correct solution in my [first comment in this present issue](https://github.com/ltsp/ltsp/issues/43#issuecomment-541269010). I.e. you just need to tell `ltsp image` that you have a separate boot partition.

**Comment by danboid** [comment]
I skipped trying that because the person who tried it said it didn't work for them.

It seems to me that command::

```
ltsp image /,,/boot,subdir=boot
```

Should be added to the installation guide as most people won't find it in the man page. I expect it applies to everyone who installs Ubuntu using ZFS.

**Comment by alkisg** [comment]
The correct `ltsp image` command line didn't work for him because there was a bug then, which is what was resolved in this issue months ago.

But you're right, an example should be included in the ltsp image man page as it's not an uncommon use case to have a separate boot partition.

**Comment by danboid** [comment]
I'm recommending this command be included within the main installation guide, or at least it should be mentioned that is command is in the man page in the install guide if not.

**Comment by gilbertoferreira** [comment]
> Ah that's a second problem. It's probably caused because overlayfs doesn't use the "merged view" of the mounts by default, but only a single mount. In LTSP5, we handled that with [additional overlay mounts](https://git.launchpad.net/ltsp/tree/server/ltsp-update-image#n149), we should probably do the same here.
> 
> I'll need a few days to resolve that; in the mean time, please do something like this as a workaround:
> 
> ```shell
> mount --bind / /mnt
> cp -a /boot/. /mnt/boot/
> umount /mnt
> ltsp image /
> ```
> 
> I.e. copy the contents of the /boot partition to the /boot folder of the / partition, before calling `ltsp image /`.

This works for me.
2022 and still have this bug!

**Comment by alkisg** [comment]
Hi, this issue has been solved years ago, please read the man page.

https://ltsp.org/man/ltsp-image/#examples

> Inform ltsp image that a chrootless installation uses separate /boot and /opt partitions:

```
ltsp image /,,/boot,subdir=boot,,/opt,subdir=opt
```

**Comment by gilbertoferreira** [comment]
> Hi, this issue has been solved years ago, please read the man page.
> 
> https://ltsp.org/man/ltsp-image/#examples
> 
> > Inform ltsp image that a chrootless installation uses separate /boot and /opt partitions:
> 
> ```
> ltsp image /,,/boot,subdir=boot,,/opt,subdir=opt
> ```

Oh! I see! 
This is not in the main documentation which I was used as a guideline.
I did saw that in the "Maintaining a client image" section, so that made me confused.

Sorry
