### ISSUE TITLE
Snaps fail to run

### ISSUE THREAD

**Issue by fottsia** [ltsp/ltsp#44]
Snaps won't run in the new LTSP, for example:

```shell
$ ubuntu-mate-welcome
cannot create lock directory /run/snapd/lock: Permission denied
```

**Comment by alkisg** [comment]
At that point, journalctl shows:

> Οκτ 13 09:36:42 pc01 audit[3390]: AVC apparmor="DENIED" operation="open" profile="/snap/core/7917/usr/lib/snapd/snap-confine" name="/up/" pid=3390 comm="snap-confine" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Οκτ 13 09:36:42 pc01 kernel: audit: type=1400 audit(1570948602.715:324): apparmor="DENIED" operation="open" profile="/snap/core/7917/usr/lib/snapd/snap-confine" name="/up/" pid=3390 comm="snap-confine" requested_mask="r" denied_mask="r" fsuid=0 ouid=0

On the other hand, the rule that snap-confine generates for apparmor is:

```shell
$ cat /var/lib/snapd/apparmor/snap-confine/overlay-root
  # snapd autogenerated workaround for systems using '/' on overlayfs. For
  # details see: https://bugs.launchpad.net/apparmor/+bug/1703674
  "/run/initramfs/ltsp/up/{,**/}" r,
```

I.e. apparmor sees /up, which is the path starting from our tmpfs, while snap-confine puts the whole path, /run/initramfs/ltsp/up.

Ubuntu live CDs had a similar problem, read [the comment of this commit](https://github.com/snapcore/snapd/pull/4714/files#diff-d42c903eb52ea8ef3ed07cf9313339e3R31).

The workaround is to put the mount source ($tmpfs) in the mount -t overlay command, so that snap-confine can then remove that prefix.
