### ISSUE TITLE
Implement ltsp remoteapps

### ISSUE THREAD

**Issue by fottsia** [ltsp/ltsp#597]
Something like the LTSP5 "remoteapps" would be great for schools; we would be able to allow students to run `mate-about-me` remotely on the server and change their display name or password.

**Comment by intelliant01** [comment]
See https://github.com/ltsp/ltsp/issues/148#issuecomment-686927698.

**Comment by alkisg** [comment]
I uploaded an initial implementation, but it's currently undocumented. It should be available in the ltsp-proposed PPA in a while.
To run an application remotely, use: `ltsp remoteapps app params`
It will configure the user ssh keys so that they're allowed to ssh without typing a password, and then it will run `ssh -X server app params`.

To register some remoteapps for all users, put something like this in ltsp.conf:

```shell
[clients]
POST_INIT_REMOTEAPPS="ltsp remoteapps --register users-admin mate-about-me"
```

Then they'll be able to run the applications normally from the menus.
Note that password changes take effect immediately, while the user display name takes effect after the sysadmin run `ltsp initrd` and the client is rebooted.

Please test and report back; if it works without issues, I'll add documentation and make it official.

**Comment by intelliant01** [comment]
@alkisg You just nixed my hack. :)

Waiting for the ppa changes to propagate before I can test.

For those who can't upgrade to proposed or while the perfect solution is released, herein is a workaround -
```
# cat > /srv/ltsp/<chroot>/usr/bin/custom-mate-about-me <<- EOF
#!/bin/bash

ssh -X server mate-about-me
zenity --info --no-wrap --title="Reboot Required" --text="Reboot to see your changes to the profile."
EOF

# chmod a+x /srv/ltsp/<chroot>/usr/bin/custom-mate-about-me
# ltsp image <chroot>
```

Add to the `[clients]` section in ltsp.conf -
```
POST_INIT_PROFILE_UPDATE_HACK="cp /usr/bin/custom-mate-about-me /usr/bin/mate-about-me"
```
Similarly other scripts may be customised / overriden.
This does have the downside of having to enter the user password for ssh before moving ahead with the actual desired action and a small upside that notifies the user about the required reboot.

**Comment by alkisg** [comment]
I introduced a new ltsp.conf parameter called REMOTEAPPS and I added documentation:
https://ltsp.org/man/ltsp-remoteapps/

So I think this issue can be closed; feel free to comment or to reopen if something is amiss.

**Comment by intelliant01** [comment]
Tested for `users-admin` and `mate-about-me`. Works fine.

Tested by applying the commit manually as proposed ppa changes have not yet propagated for me via `apt update`.

**Comment by alkisg** [comment]
Yeah launchpad seems busy, we need to wait for the green tick marks at:
https://code.launchpad.net/~ltsp/+archive/ubuntu/proposed/+packages

Thanks for testing! Later on when the http service is implemented, the clients won't even need to be rebooted...

**Comment by alkisg** [comment]
I wonder if it would be better for LTSP to create its own key, and tell ssh to use it with `ssh -i ~/.config/ltsp/id_ed25519`. Of course it would also add the public part to the user's authorized_keys.

That way if users wanted to `ssh server` for some other reason, they'd be asked for a password as the special ltsp ssh key wouldn't be used.

@vagrantc, any thoughts on this?
