### ISSUE TITLE
ltsp.img copying into client rootfs: allow chroot based tweaks by file drop-ins

### ISSUE THREAD

**Issue by sunweaver** [ltsp/ltsp#636]
@alkisg As we discussed on #ltsp IRC today, it would be cool to adjust the ltsp.img copying of files in a way that it becomes possible to tweak individuel chroots by adding vendor specific files into the chroot and by this influence the start-up procedure of an LTSP client.

This would provide a means to adjust different chroots in their start up behaviour without putting to many environment specific details into /etc/ltsp/ltsp.conf (such as client name patterns or such).

The discussion came up because I wanted to run x2gothinclient-minidesktop on top of LTSP in Debian bullseye.

The minidesktop package (installed inside of a chroot) drops a file into /usr/share/ltsp/client/init/ as 88-&lt;something>. Currently, this file gets removed from the chroot as /usr/share/ltsp/ gets cleaned up and overwritten by install_ltsp().

It would be cool to see that related patch in Debian bullseye via a stable-update upload. I can help with that if needed.

**Comment by alkisg** [comment]
Thanks, fixed committed. I also triggered a proposed PPA build.
It would be nice to test all of the new LTSP package instead of just this patch, as it'll be released on Debian soon, in order for this version to make it for Ubuntu 22.04.

@sunweaver, talk with @vagrantc about the stable-update upload, and whether it should be just the patch or the whole new version in backports, I'm a lot less familiar with the upload process than you guys, so I'll let you take care of that part! :)

**Comment by vagrantc** [comment]
seems more appropriate for Debian backports, but if the patch is small enough maybe it could go into a Debian bullseye point release...

**Comment by sunweaver** [comment]
@vagrantc: it would be coolio to have this patch injected into bullseye via bullseye-propose-updates:

https://github.com/ltsp/ltsp/commit/1db2233525e3b1de66376910182b894541bcc285

**Comment by sunweaver** [comment]
Shall I do that?

**Comment by alkisg** [comment]
In 1db2233, the `2>/dev/null` part isn't needed; I just removed it upstream, if you want you may also omit it from the backported patch for consistency.
