### ISSUE TITLE
remote access to the server

### ISSUE THREAD

**Issue by Plekhanov-sgu** [ltsp/ltsp#641]
Good time Alkis, tell me please. How to properly organize the setting so that there are no conflicts. The image given in the terminal classes is built on a powerful server. It is required to use the power of the server in parallel with the terminal classes to analyze the data array. There must be remote access to the server to download data and run the data analysis program. Network configuration with two memory cards.

P.S. LTSP has been running flawlessly for 3 years now, with 10 out of 30 computers connected to cameras for remote lessons with GoogleMeet, Zoom and Skype. Thanks Alkis for your work.

**Comment by alkisg** [comment]
Hello @Plekhanov-sgu , thank you for your good words,

please open a discussion in this page: https://github.com/ltsp/ltsp/discussions

...because https://github.com/ltsp/ltsp/issues are for bug in the LTSP code, not for general discussions...

Please also specify your setup in more detail, so that people that will try to help you will know what you're asking for.
