### ISSUE TITLE
pamltsp should (maybe) ping server before attempting to mount home dirs

### ISSUE THREAD

**Issue by danboid** [ltsp/ltsp#645]
LTSP / pa,ltsp expects $SERVER to have been defined and to be up. I think it would be good if pamltsp printed an error to say something like "LTSP cannot contact $SERVER, check $SERVER definition in ltsp.conf"  in case the user has forgotten to define $SERVER in ltsp.conf, presuming they are not using server as the hostname of the LTSP server. This could work in the form of a ping test before it tries to mount (or after it fails to mount) the home dirs.

This should also probably be mentioned in the installation guide (before running `ltsp initrd`) because it seems this might be the only ltsp.conf variable that must be defined correctly for logins to work, in many cases.

**Comment by alkisg** [comment]
I'm in favour of maintaining only the basic documentation upstream, so that the users will be able to read all of it.
For pointing SSH_SERVER to another server, feel free to create and maintain a wiki page:
https://github.com/ltsp/ltsp/wiki

About pinging SERVER when the LTSP client boots, it doesn't make much sense as it'll be up anyway, as it's used for the NFS mount.
About pinging SSH_SERVER from PAM, the message won't be visible to the user because pamltsp runs behind the scenes. Logging the result of the ping in a log file won't really help.
