### ISSUE TITLE
DISABLE_SYSTEM_SERVICES doesn't always work

### ISSUE THREAD

**Issue by fottsia** [ltsp/ltsp#690]
In some installations, adding for example `DISABLE_SYSTEM_SERVICES="xrdp"` doesn't take effect, xrdp is still running in the LTSP clients.
I've only been able to reproduce this issue in some installations, not in all of them. Additionally, I haven't been able to reproduce it in Ubuntu 22.04.

**Comment by alkisg** [comment]
I think this is related to the [UsrMerge migration](https://wiki.debian.org/UsrMerge), where /lib is updated to be a symlink to /usr/lib. Older systems such as Ubuntu <= 18.04 or even half the 20.04 installation that I've checked, have a separate /lib, while in newer installations like Ubuntu 22.04 /lib is a symlink.

I updated 56-services.sh to also search in /lib for systemd units. Normally I would say that this is serious enough to require a new release in time for Ubuntu 22.04, but since only older systems are affected, they can get an updated LTSP from the PPA.

I will upload a build to the proposed PPA, please test if it now works as expected!

**Comment by fottsia** [comment]
The new version works fine for me, thank you.
